version: "3.3"

services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
      - "8421:8421"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./conf:/etc/traefik"
      - "./log:/var/log/traefik"